# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci .
os: linux
dist: bionic
services:
  - docker
language: cpp
compiler: gcc
cache: ccache

notifications:
  email: true

env:
  global:
    - DOCKER_IMAGE=moveit/moveit2:eloquent-source
    # - UPSTREAM_WORKSPACE=.rosinstall

jobs:
  - env: TEST=clang-format
  - env: TEST=code-coverage
  - compiler: clang
    env: DOCKER_IMAGE=moveit/moveit2:master-source

before_script:
  - git clone -q -b ros2 --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
